"""Assemble the thirst/water design page: house chrome + script-drawn figures + dashboard renders.

  python build_page.py      # writes docs/develop/active/thirst/thirst_water.html

The builder EMBEDS, it never draws (guide 2.7). It fails rather than shipping a partial page: a
figure with no script, a missing raster or data statement, a caption with no axes sentence, a figure
with no method block, a method block that never says what the figure does NOT show, vector art drawn
inside a <figure>, figure numbers out of order, or any unsubstituted token.

Dashboard renders (stems starting `render_`) are PNGs made by the rendering session's own tooling
(src/environment/dashboard/); they carry a data/kind statement written by render_notes.py and a
`<stem>.source.txt` naming the command that produced them, instead of a matplotlib script here.
"""
import base64, os, re, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "..", ".."))
HOUSE = os.path.join(ROOT, "docs/develop/active/meta/house_style_sheet.html")
HERE = os.path.join(ROOT, "docs/develop/active/thirst")
TPL = os.environ.get("THIRST_TPL", os.path.join(HERE, "thirst_water.template.html"))   # override: trial builds only
OUT = os.environ.get("THIRST_OUT", os.path.join(HERE, "thirst_water.html"))
FIGS = os.path.join(HERE, "figures")
SCRIPTS = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPTS)
import _common as CC                                              # noqa: E402

fail = []


def die():
    if fail:
        for f in fail:
            print("  BUILD FAILURE:", f)
        sys.exit(1)


house = open(HOUSE).read()
style = re.search(r"<style>.*?</style>", house, re.S)
script = re.search(r"<script>.*?</script>", house, re.S)
viewer = re.search(r'<div class="lb fit" id="lb".*?\n</div>', house, re.S)
if not (style and script and viewer):
    fail.append("could not lift the house <style>, viewer markup and <script> from the built sheet"); die()

page = open(TPL).read()
page = page.replace("__HOUSE_STYLE__", style.group(0))
assert page.count("__HOUSE_SCRIPT__") == 1
page = page.replace("__HOUSE_SCRIPT__", viewer.group(0) + "\n" + script.group(0))
stems = sorted(set(re.findall(r'data-fig="([^"]+)"', page)))

for stem in stems:
    df = os.path.join(FIGS, f"{stem}.data.txt")
    if not os.path.exists(df):
        fail.append(f"{stem}: no {stem}.data.txt"); continue
    rows = [l.rstrip("\n").split("|") for l in open(df) if l.strip()]
    cells = "".join(f'<tr><td>{w}</td><td class="n">{u}</td><td class="n">{t}</td><td class="n">{p}%</td><td>{n}</td></tr>'
                    for w, u, t, p, n in rows)
    block = ('<span><b>Data.</b> How much this figure used, emitted by its own script:</span>'
             '<p class="cue" hidden>Wider than the screen — scroll sideways; the right-hand columns are cut off.</p>'
             '<div class="scroll"><table class="datatable"><thead><tr><th>subset</th>'
             '<th class="n">used</th><th class="n">available</th><th class="n">share</th>'
             f'<th>why</th></tr></thead><tbody>{cells}</tbody></table></div>')
    if stem.startswith("render_"):
        src = os.path.join(FIGS, f"{stem}.source.txt")
        if not os.path.exists(src):
            fail.append(f"{stem}: no {stem}.source.txt naming the command that rendered it"); continue
        srctxt = open(src).read().strip()
        if "PENDING" in srctxt and not os.environ.get("THIRST_ALLOW_PENDING"):
            fail.append(f"{stem}: {stem}.source.txt still says PENDING - get the render command first")
        path = re.sub(r"([._/])", r"\1<wbr>", srctxt.split()[0])
        block += (f'<p class="prov">Rendered by <code>{path}</code>\u2060 from the repo root; the level-06 '
                  f'recordings it reads are regenerated by the commands in its docstring. The table above is '
                  f'<code>figures/<wbr>{stem}.<wbr>data.<wbr>txt</code>\u2060, written by <code>render_<wbr>notes.<wbr>py</code>.</p>')
    else:
        block += (f'<p class="prov">Drawn by <code>scripts/<wbr>analysis/<wbr>studies/<wbr>thirst_water/<wbr>{stem}.py</code>⁠, '
                  f'which also writes <code>figures/<wbr>{stem}.data.txt</code>⁠ — the table above.</p>')
    page = page.replace(f"__DATA:{stem}__", block)

for stem in stems:
    kf = os.path.join(FIGS, f"{stem}.kind.txt")
    if not os.path.exists(kf):
        fail.append(f"{stem}: no {stem}.kind.txt"); continue
    k = open(kf).read().strip()
    page = page.replace(f"__KIND:{stem}__", f'<p class="kind kind-{k}">{CC.KIND[k]}</p>')

for stem in stems:
    png = os.path.join(FIGS, f"{stem}.png")
    if not os.path.exists(png):
        fail.append(f"{stem}: {stem}.png is missing"); continue
    if not stem.startswith("render_"):
        if not os.path.exists(os.path.join(SCRIPTS, f"{stem}.py")):
            fail.append(f"{stem}: no generating script {stem}.py (guide 5)")
        if not os.path.exists(os.path.join(FIGS, f"{stem}.svg")):
            fail.append(f"{stem}: no vector companion {stem}.svg")
    b64 = base64.b64encode(open(png, "rb").read()).decode()
    page = re.sub(rf'(<img data-fig="{re.escape(stem)}")', rf'\1 src="data:image/png;base64,{b64}"', page, count=1)

# --- register F69: code chips in table cells break only after . _ / (never mid-identifier) -----
def _chip(m):
    return "<code>" + re.sub(r"(?<!<wbr>)([._/])(?!<wbr>)", r"\1<wbr>", m.group(1)) + "</code>"
page = re.sub(r"<td([^>]*)>(.*?)</td>",
              lambda m: f"<td{m.group(1)}>" + re.sub(r"<code>(.*?)</code>", _chip, m.group(2), flags=re.S) + "</td>",
              page, flags=re.S)

# --- script-emitted table fragments (numbers never typed into the template) -------------------
for m in set(re.findall(r"__TABLE:([a-z0-9_]+)__", page)):
    tf = os.path.join(FIGS, f"{m}.html")
    if not os.path.exists(tf):
        fail.append(f"table fragment {m}.html missing - run its script"); continue
    page = page.replace(f"__TABLE:{m}__", open(tf).read())

seen = []
for m in re.finditer(r"<figure>.*?</figure>", page, re.S):
    blk = m.group(0); flat = re.sub(r"\s+", " ", blk)
    sm = re.search(r'data-fig="([^"]+)"', blk); stem = sm.group(1) if sm else "<no data-fig>"
    for need, msg in (('src="data:image/png;base64,', "raster never embedded"), ("<b>Axes.</b>", "no Axes sentence (11a)"),
                      ("<b>Data.</b>", "no data block (11b)"), ("<b>How it is computed.</b>", "no method block (11c)"),
                      ('class="kind kind-', "no kind badge"), ("zoomhint", "no click-to-open hint (2.6)")):
        if need not in (blk if need.startswith("src") else flat):
            fail.append(f"{stem}: {msg}")
    if "<b>How it is computed.</b>" in flat and "does not show" not in flat:
        fail.append(f"{stem}: method block never says what the figure does NOT show (11c)")
    if re.search(r"<(svg|canvas)\b", blk):
        fail.append(f"{stem}: vector art drawn in the page (2.7)")
    alt = re.search(r'alt="([^"]*)"', blk)
    if not alt or len(alt.group(1)) < 60:
        fail.append(f"{stem}: alt text missing or too short")
    meth = re.search(r"<b>How it is computed\.</b>(.*?)</span>", flat)
    if meth:
        wc = len(re.sub(r"<[^>]+>", " ", meth.group(1)).split())
        if not 120 <= wc <= 300:
            fail.append(f"{stem}: method block is {wc} words (guide 11c: ~150-250)")
    fn = re.search(r"<b>Figure (\d+)", flat)
    if not fn:
        fail.append(f"{stem}: caption has no 'Figure N'")
    else:
        seen.append(int(fn.group(1)))
if seen != list(range(1, len(seen) + 1)):
    fail.append(f"figure numbers are not 1..N in document order: {seen}")

for tm in re.finditer(r"<table[^>]*>", page):
    before = page[max(0, tm.start() - 400):tm.start()]
    if 'class="scroll"' not in before or '<p class="cue"' not in before:
        fail.append(f"a <table> lacks its scroll box or overflow cue: {tm.group(0)[:60]}")

_tm = re.search(r"<title>(.*?)</title>", page); _hm = re.search(r"<h1>(.*?)</h1>", page)
if not (_tm and _hm and _tm.group(1).strip() == _hm.group(1).strip()):
    fail.append("<title> does not match <h1>")
if page.count("<section") != page.count("</section>"):
    fail.append("<section> open/close counts differ")
left = re.findall(r"__[A-Z][A-Z0-9_:]*__|\{\{[^}]+\}\}", page)
if left:
    fail.append(f"unsubstituted tokens remain: {sorted(set(left))[:6]}")
if "data:font" not in page:
    fail.append("no embedded font")
die()
page = '<meta charset="utf-8">\n' + page
open(OUT, "w").write(page)
print(f"wrote {os.path.relpath(OUT, ROOT)}  ({len(page)/1e6:.2f} MB, {len(seen)} figures)")
