"""Off = today: the five body mechanics change nothing at their off values.

**Plain-language summary.** `docs/develop/active/thermal/STATE_DEPENDENT_BODY_MECHANICS.md`
adds five mechanics that make the best action depend on combinations of internal states
(B1 random start temperature, B2 healing needs warmth, B3 healing costs food, B4 injury
speeds heat exchange, B5 healing speed depends on food). Every one ships with an exact
"off" value. This test is the proof that "off" means the environment behaves exactly as it
did before the change, three ways:

1. **Rollouts.** 16 seeds x 300 steps in curriculum levels 05 (campfire) and 04, compared
   with `np.array_equal` — no tolerance — against rollouts recorded from a worktree of the
   pre-change commit (`tests/env/fixtures/body_mechanics_parity/pre_change_rollouts.npz`,
   generated by `scripts/fixtures/generate_body_mechanics_parity_fixture.py`, whose
   rollout loop this test imports rather than copies).
2. **Graphs.** The `jax_step` / `jax_reset` / `update_body` jaxpr strings (params
   traced) hash to the same SHA-1 as before. That is only possible because every new
   field is static (plan §A1, reviewer M1).
3. **Contrast.** Each mechanic, switched on, changes both the rollout and the relevant
   jaxpr — so (1) and (2) cannot pass merely because the mechanic was never wired in.

Level 05 enables B1 (a random start temperature) in its config after commit C3. This test
switches it back off IN MEMORY (`thermal.random_start_body_temp: false`, unconditional)
and prints that it did; everything else is the world as resolved at HEAD. A named drift
check compares the resolved config (minus the fifteen new keys) with the one stamped into
the fixture, so unrelated config drift fails with its own message.

Fails — never skips — on a missing fixture, config or provenance. CPU only (conftest).
"""
import copy
import os
import sys

import jax
import jax.numpy as jnp
import numpy as np
import pytest
import yaml

_REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, os.path.join(_REPO, "scripts", "fixtures"))
import generate_body_mechanics_parity_fixture as G  # noqa: E402

import src.environment.core as core  # noqa: E402
from src.environment.config_loader import load_env_config, load_env_params  # noqa: E402
from src.environment.sensor import get_observation  # noqa: E402
from src.utils.config import Config  # noqa: E402

FIXTURE = os.path.join(_REPO, G.OUT_REL)

NEW_KEYS = (
    "thermal.random_start_body_temp", "thermal.start_body_temp_low",
    "thermal.start_body_temp_high", "thermal.healing_cold_sensitivity",
    "thermal.healing_warm_sensitivity", "thermal.injury_heat_exchange_gain",
    "thermal.injury_heat_exchange_mode",
    "body.healing_nutrition_cost", "body.healing_nutrition_shortfall",
    "body.healing_nutrition_dependence", "body.healing_hunger_low",
    "body.healing_hunger_high", "body.healing_hunger_floor",
    "body.healing_overfull_floor", "body.healing_overfull_start",
)
assert len(NEW_KEYS) == 15

# Keys added by LATER changes, inert at their shipped value, that the resolved level-05
# config now carries but this fixture predates. Dropped only in the drift check; their own
# off-parity is proved elsewhere. bush_min_fire_distance: BUSH_FIRE_CLEARANCE
# (tests/env/test_bush_fire_clearance.py).
LATER_INERT_KEYS = ("thermal.bush_min_fire_distance",)

CONTRAST_SEEDS = (0, 1, 2, 3)


@pytest.fixture(autouse=True)
def _release_compiled_programs():
    """Drop this test's compiled programs afterwards.

    Each distinct world compiles its own step/reset programs, and every compiled CPU
    program holds memory mappings. Kept alive across a whole-suite run they exhaust the
    kernel's per-process limit (vm.max_map_count = 65530 here) and a LATER, unrelated
    module aborts inside XLA compilation. Measured 2026-09-26: without this, a
    `pytest tests/env` run reached 65,479 mappings and died in
    test_bush_blocks_animals.py.
    """
    yield
    jax.clear_caches()


@pytest.fixture(scope="module")
def fx():
    assert os.path.isfile(FIXTURE), (
        f"parity fixture missing: {FIXTURE}. Regenerate it from a PRE-change worktree "
        "(see the generator's docstring); never from this checkout.")
    data = np.load(FIXTURE)
    assert "_provenance_sha" in data.files, "fixture has no _provenance_sha"
    sha = str(data["_provenance_sha"])
    assert len(sha) == 40, f"bad provenance sha {sha!r}"
    return {k: data[k] for k in data.files}


def _world_dict(world):
    """The world as resolved at HEAD, with B1 forced off in memory."""
    path = os.path.join(_REPO, G.WORLDS[world])
    assert os.path.isfile(path), f"world config missing: {path}"
    d = copy.deepcopy(load_env_config(path).to_dict())
    if d["thermal"]["enabled"]:
        was = d["thermal"].get("random_start_body_temp")
        d["thermal"]["random_start_body_temp"] = False
        print(f"[parity] {world}: thermal.random_start_body_temp {was!r} -> False (in memory)")
    return d


def _drop(d, dotted_keys):
    d = copy.deepcopy(d)
    for k in dotted_keys:
        blk, key = k.split(".")
        d.get(blk, {}).pop(key, None)
    return d


def _params(d):
    return load_env_params(Config(copy.deepcopy(d)))


def _shas(params):
    state0 = core.jax_reset(params, jax.random.PRNGKey(0))
    return G.jaxpr_shas(jax, jnp, core, params, state0)


def _rollout(params, seeds=G.SEEDS, max_t=G.MAX_T):
    return G.rollout_world(jax, jnp, core, get_observation, params, seeds=seeds,
                           max_t=max_t)


@pytest.mark.parametrize("world", sorted(G.WORLDS))
def test_no_unrelated_config_drift(fx, world):
    """O3: the resolved world minus the fifteen new keys equals the stamped one."""
    stamped = yaml.safe_load(str(fx[f"{world}._config_yaml"]))
    now = _drop(_world_dict(world), NEW_KEYS + LATER_INERT_KEYS)
    stamped = _drop(stamped, NEW_KEYS + LATER_INERT_KEYS)
    if now != stamped:
        diffs = []
        for blk in sorted(set(now) | set(stamped)):
            a, b = now.get(blk), stamped.get(blk)
            if a != b:
                if isinstance(a, dict) and isinstance(b, dict):
                    ks = sorted(k for k in set(a) | set(b) if a.get(k) != b.get(k))
                    diffs.append(f"{blk}: {ks}")
                else:
                    diffs.append(blk)
        pytest.fail(f"{world}: config drifted since the fixture was recorded, outside the "
                    f"body-mechanics keys: {diffs}. Regenerate the fixture from a "
                    "pre-change worktree only if that drift is intended.")


@pytest.mark.parametrize("world", sorted(G.WORLDS))
def test_new_keys_resolve_inert(world):
    p = _params(_world_dict(world))
    assert p.thermal_random_start_body_temp is False
    assert p.thermal_healing_cold_sensitivity == 0.0
    assert p.thermal_healing_warm_sensitivity == 0.0
    assert p.thermal_injury_heat_exchange_gain == 0.0
    assert p.healing_nutrition_cost == 0.0
    assert p.healing_nutrition_dependence is False


@pytest.mark.parametrize("world", sorted(G.WORLDS))
def test_jaxpr_sha_identical(fx, world):
    """CP3/CP4: jax_step, jax_reset and update_body trace the pre-change graph."""
    now = _shas(_params(_world_dict(world)))
    for fn in ("jax_step", "jax_reset", "update_body"):
        want = str(fx[f"{world}._jaxpr_sha.{fn}"])
        print(f"[parity] {world} {fn}: {now[fn]}")
        assert now[fn] == want, f"{world}: {fn} jaxpr changed ({want} -> {now[fn]})"


@pytest.mark.parametrize("world", sorted(G.WORLDS))
def test_rollouts_byte_identical(fx, world):
    """CP3: every recorded array equal, no tolerance."""
    arrays = _rollout(_params(_world_dict(world)))
    want_keys = sorted(k[len(world) + 1:] for k in fx
                       if k.startswith(world + ".s"))
    assert sorted(arrays) == want_keys, f"{world}: recorded field set differs"
    bad = []
    for k in want_keys:
        ref, got = fx[f"{world}.{k}"], arrays[k]
        if ref.shape != got.shape or ref.dtype != got.dtype or not np.array_equal(ref, got):
            bad.append(k)
    assert not bad, f"{world}: {len(bad)} arrays differ from the pre-change fixture: {bad[:12]}"


@pytest.mark.parametrize("world", sorted(G.WORLDS))
def test_fixture_coverage(fx, world):
    """The fixture is not vacuous: healing, bush healing, deaths and eating all occur."""
    arrays = {k[len(world) + 1:]: v for k, v in fx.items() if k.startswith(world + ".s")}
    c = G.coverage(arrays, None, world)
    print(f"[parity] {world} coverage: {c}")
    G.check_coverage(c, world)


# ── Contrast half: each mechanic ON changes the rollout AND the jaxpr ─────────

def _set(d, dotted, value):
    blk, key = dotted.split(".")
    d[blk][key] = value


_B5 = {"body.healing_nutrition_dependence": True, "body.healing_hunger_low": 20.0,
       "body.healing_hunger_high": 100.0, "body.healing_hunger_floor": 0.2,
       "body.healing_overfull_floor": 1.0}

CONTRASTS = {
    # name: (world, overrides, jaxpr function that must change)
    "B1_pinned_minus5": ("lvl05", {"thermal.random_start_body_temp": True,
                                   "thermal.start_body_temp_low": -5.0,
                                   "thermal.start_body_temp_high": -5.0}, "jax_reset"),
    "B2_cold": ("lvl05", {"thermal.healing_cold_sensitivity": 0.1}, "jax_step"),
    "B3_partial_lvl05": ("lvl05", {"body.healing_nutrition_cost": 1.0,
                                   "body.healing_nutrition_shortfall": "partial"}, "jax_step"),
    "B3_full_lvl05": ("lvl05", {"body.healing_nutrition_cost": 1.0,
                                "body.healing_nutrition_shortfall": "full"}, "jax_step"),
    "B3_partial_lvl04": ("lvl04", {"body.healing_nutrition_cost": 1.0,
                                   "body.healing_nutrition_shortfall": "partial"}, "jax_step"),
    "B3_full_lvl04": ("lvl04", {"body.healing_nutrition_cost": 1.0,
                                "body.healing_nutrition_shortfall": "full"}, "jax_step"),
    "B4_cooling_only": ("lvl05", {"thermal.injury_heat_exchange_gain": 1.0,
                                  "thermal.injury_heat_exchange_mode": "cooling_only"},
                        "jax_step"),
    "B4_both": ("lvl05", {"thermal.injury_heat_exchange_gain": 1.0,
                          "thermal.injury_heat_exchange_mode": "both"}, "jax_step"),
    "B5": ("lvl05", dict(_B5), "jax_step"),
    "B5_overfull": ("lvl05", {**_B5, "body.healing_overfull_floor": 0.5,
                              "body.healing_overfull_start": 150.0}, "jax_step"),
}


def _differs(fx, world, arrays):
    for k, got in arrays.items():
        ref = fx[f"{world}.{k}"]
        if ref.shape != got.shape or not np.array_equal(ref, got):
            return True
    return False


@pytest.mark.parametrize("name", sorted(CONTRASTS))
def test_contrast_mechanic_on_changes_rollout_and_graph(fx, name):
    world, overrides, fn = CONTRASTS[name]
    d = _world_dict(world)
    for k, v in overrides.items():
        _set(d, k, v)
    p = _params(d)
    shas = _shas(p)
    assert shas[fn] != str(fx[f"{world}._jaxpr_sha.{fn}"]), (
        f"{name}: switching the mechanic on did not change the {fn} jaxpr — it is not "
        "wired in, so the off-path equality proves nothing")
    arrays = _rollout(p, seeds=CONTRAST_SEEDS)
    assert _differs(fx, world, arrays), f"{name}: rollout identical to the off fixture"


def test_contrast_B2_warm_in_a_warm_scene():
    """B2 warm side needs a body above its setpoint while healing: a uniform +8 world
    (no fires, so the body settles near +5.3). s_w = 0.1 must change that rollout."""
    base = _world_dict("lvl05")
    base["thermal"]["use_object_sources"] = False
    base["thermal"]["use_random_spots"] = False
    base["thermal"]["default_temp"] = [8.0, 8.0]
    warm = copy.deepcopy(base)
    warm["thermal"]["healing_warm_sensitivity"] = 0.1
    p0, p1 = _params(base), _params(warm)
    assert _shas(p0)["jax_step"] != _shas(p1)["jax_step"]
    a0 = _rollout(p0, seeds=CONTRAST_SEEDS)
    a1 = _rollout(p1, seeds=CONTRAST_SEEDS)
    bt = np.concatenate([a0[f"s{s}.state.body_temp"] for s in CONTRAST_SEEDS])
    assert bt.max() > 1.0, "the warm scene never got the body above its setpoint"
    assert any(not np.array_equal(a0[k], a1[k]) for k in a0), (
        "s_w = 0.1 did not change the warm-scene rollout")
