"""Keep bushes away from campfires: `thermal.bush_min_fire_distance`.

**Plain-language summary.** `docs/develop/active/thermal/BUSH_FIRE_CLEARANCE.md` adds a
world-generation rule that keeps every bush (a hiding spot) at least `v` grid steps
(Manhattan) from every burning campfire, so that one cell can no longer be both safe from
predators and warm. It ships OFF (`0`). This file proves:

1. **Off = today, exactly.** At `0` the `jax_reset` / `jax_step` graphs hash to the same
   SHA-1 as the pre-change code, and 64 reset states per world are `np.array_equal` (no
   tolerance) to states recorded from a worktree of the pre-change commit
   (`tests/env/fixtures/bush_fire_clearance_parity/pre_change_resets.npz`, generated by
   `scripts/fixtures/generate_bush_fire_clearance_parity_fixture.py`).
2. **On does what it says.** Over 1,000 resets, no active bush sits at Manhattan `< v`
   from a burning fire, every bush stays inside its own spawn area (the silent (0, 0)
   fallback never fires), and no two active entities share a cell.
3. **On moves only bushes.** With the same seeds, every reset leaf except bush positions
   is identical to the rule-off world, including the thermal field and the fires.
4. **The loader refuses** the values and worlds the rule cannot serve, each with its own
   message.

Fails -- never skips -- on a missing fixture. CPU only (conftest).
"""
import copy
import os
import sys

import jax
import jax.numpy as jnp
import numpy as np
import pytest
import yaml

_REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, os.path.join(_REPO, "scripts", "fixtures"))
import generate_bush_fire_clearance_parity_fixture as G  # noqa: E402
from generate_body_mechanics_parity_fixture import jaxpr_shas  # noqa: E402

import src.environment.core as core  # noqa: E402
from src.environment.config_loader import load_env_config, load_env_params  # noqa: E402
from src.utils.config import Config  # noqa: E402

FIXTURE = os.path.join(_REPO, G.OUT_REL)
KEY = "thermal.bush_min_fire_distance"
LVL05 = os.path.join(_REPO, G.WORLDS["lvl05"][0])
N_RESETS = 1000


@pytest.fixture(autouse=True)
def _release_compiled_programs():
    """Drop compiled programs afterwards (see test_body_mechanics_parity.py: a whole-suite
    run otherwise exhausts vm.max_map_count)."""
    yield
    jax.clear_caches()


@pytest.fixture(scope="module")
def fx():
    assert os.path.isfile(FIXTURE), (
        f"parity fixture missing: {FIXTURE}. Regenerate it from a PRE-change worktree "
        "(see the generator's docstring); never from this checkout.")
    data = np.load(FIXTURE)
    assert "_provenance_sha" in data.files, "fixture has no _provenance_sha"
    sha = str(data["_provenance_sha"])
    assert len(sha) == 40, f"bad provenance sha {sha!r}"
    return {k: data[k] for k in data.files}


# ── helpers ───────────────────────────────────────────────────────────────────

def _world(world):
    cfg, params = G.load_world(load_env_config, load_env_params, _REPO, world)
    return cfg, params


def _lvl05_dict(**thermal):
    d = copy.deepcopy(load_env_config(LVL05).to_dict())
    d["thermal"].update(thermal)
    return d


def _obstacle(d, name):
    for o in d["environment"]["obstacles"]:
        if o.get("name") == name:
            return o
    raise AssertionError(f"obstacle {name!r} missing from the level-05 config")


def _fix_count(entry, n):
    entry.pop("count_low", None)
    entry.pop("count_high", None)
    entry["count"] = n


def _params(d):
    return load_env_params(Config(copy.deepcopy(d)))


def _resets(params, n=N_RESETS, offset=0):
    keys = jax.vmap(jax.random.PRNGKey)(jnp.arange(offset, offset + n))
    return jax.jit(jax.vmap(core.jax_reset, in_axes=(None, 0)))(params, keys)


def _masks(params):
    fire = np.asarray(core.heat_source_mask(
        np.asarray(params.obs_temperature), np.asarray(params.obs_temp_ratio_low),
        np.asarray(params.obs_temp_ratio_high)), dtype=bool)
    bush = np.asarray(params.obs_hides_agent, dtype=bool) & ~fire
    return fire, bush


def _manhattan(a, b):
    """a [..., n, 2], b [..., m, 2] -> [..., n, m]."""
    return np.abs(a[..., :, None, :] - b[..., None, :, :]).sum(-1)


def _check_world(params, states, v):
    """Returns (violations, out_of_area, shared_cells) over every reset in `states`."""
    fire, bush = _masks(params)
    obs_pos = np.asarray(states.obs_pos)
    act = np.asarray(states.obs_active)
    burning = act & fire[None, :]
    active_bush = act & bush[None, :]
    d = _manhattan(obs_pos[:, bush], obs_pos[:, fire])          # [R, n_bush, n_fire]
    near = (d < v) & burning[:, fire][:, None, :] & active_bush[:, bush][:, :, None]
    violations = int(near.any(axis=(1, 2)).sum())

    area = np.asarray(params.obs_spawn_area)[bush]                # [nb, 4] 0-based [r0,c0,r1,c1)
    bp = obs_pos[:, bush]
    inside = ((bp[..., 0] >= area[:, 0]) & (bp[..., 0] < area[:, 2])
              & (bp[..., 1] >= area[:, 1]) & (bp[..., 1] < area[:, 3]))
    out_of_area = int((active_bush[:, bush] & ~inside).sum())

    H, W = params.height, params.width
    shared = 0
    res_pos, res_act = np.asarray(states.res_pos), np.asarray(states.res_active)
    an_pos, an_act = np.asarray(states.animal_pos), np.asarray(states.animal_active)
    for r in range(obs_pos.shape[0]):
        cells = np.concatenate([res_pos[r][res_act[r]], an_pos[r][an_act[r]],
                                obs_pos[r][act[r]]], axis=0)
        cells = cells[(cells[:, 0] < H) & (cells[:, 1] < W)]
        flat = cells[:, 0] * W + cells[:, 1]
        shared += int(len(flat) - len(np.unique(flat)))
    return violations, out_of_area, shared


# ── 1. off = today ────────────────────────────────────────────────────────────

@pytest.mark.parametrize("world", sorted(G.WORLDS))
def test_no_unrelated_config_drift(fx, world):
    """The resolved world minus the new key equals the one stamped into the fixture."""
    stamped = yaml.safe_load(str(fx[f"{world}._config_yaml"]))
    cfg, _ = _world(world)
    now = copy.deepcopy(cfg.to_dict())
    now.get("thermal", {}).pop("bush_min_fire_distance", None)
    assert "bush_min_fire_distance" not in stamped.get("thermal", {}), (
        "the fixture was recorded from code that already had the key: not pre-change")
    if now != stamped:
        diffs = sorted(b for b in set(now) | set(stamped) if now.get(b) != stamped.get(b))
        pytest.fail(f"{world}: config drifted since the fixture was recorded, outside "
                    f"{KEY}: blocks {diffs}. Regenerate the fixture from a pre-change "
                    "worktree only if that drift is intended.")


@pytest.mark.parametrize("world", sorted(G.WORLDS))
def test_off_value_resolves_to_zero(world):
    _, params = _world(world)
    assert params.thermal_bush_min_fire_distance == 0


@pytest.mark.parametrize("world", sorted(G.WORLDS))
def test_off_jaxpr_identical(fx, world):
    """jax_reset and jax_step trace the pre-change graph at value 0."""
    _, params = _world(world)
    shas = jaxpr_shas(jax, jnp, core, params, core.jax_reset(params, jax.random.PRNGKey(0)))
    for fn in G.JAXPR_FNS:
        assert shas[fn] == str(fx[f"{world}._jaxpr_sha.{fn}"]), (
            f"{world}: {fn} jaxpr changed at {KEY}=0")


@pytest.mark.parametrize("world", sorted(G.WORLDS))
def test_off_resets_byte_identical(fx, world):
    """Every EnvState leaf of 64 resets equals the pre-change fixture, no tolerance."""
    _, params = _world(world)
    now = G.reset_leaves(jax, core, params)
    stored = {k[len(f"{world}.reset."):]: v for k, v in fx.items()
              if k.startswith(f"{world}.reset.")}
    assert stored, f"{world}: no reset leaves in the fixture"
    assert set(now) == set(stored), f"{world}: EnvState leaves differ: " \
        f"{sorted(set(now) ^ set(stored))}"
    bad = [k for k in sorted(stored) if not np.array_equal(now[k], stored[k])]
    assert not bad, f"{world}: reset leaves differ from the pre-change fixture: {bad}"


# ── 2. on does what it says ───────────────────────────────────────────────────

@pytest.mark.parametrize("v", [3, 2])
@pytest.mark.parametrize("scene", ["stress", "natural"])
def test_no_bush_near_a_fire(v, scene):
    d = _lvl05_dict(bush_min_fire_distance=v)
    if scene == "stress":
        _fix_count(_obstacle(d, "campfire"), 3)
        _fix_count(_obstacle(d, "bush"), 10)
    params = _params(d)
    assert params.thermal_bush_min_fire_distance == v
    states = _resets(params)
    violations, out_of_area, shared = _check_world(params, states, v)
    print(f"[bush-clearance] v={v} {scene}: {N_RESETS} resets, violations={violations}, "
          f"out_of_area={out_of_area}, shared_cells={shared}")
    assert violations == 0, f"{violations} resets have a bush at Manhattan < {v} from a fire"
    assert out_of_area == 0, f"{out_of_area} bushes outside their spawn area ((0,0) park?)"
    assert shared == 0, f"{shared} shared cells among active entities"

    # Non-vacuous: at 0 the same seeds DO put bushes near fires.
    off = _params(_lvl05_dict(bush_min_fire_distance=0) if scene == "natural" else
                  (lambda dd: (_fix_count(_obstacle(dd, "campfire"), 3),
                               _fix_count(_obstacle(dd, "bush"), 10), dd)[-1])(
                      _lvl05_dict(bush_min_fire_distance=0)))
    v_off, _, _ = _check_world(off, _resets(off), v)
    assert v_off > 0, "rule-off world never has a bush near a fire: the check is vacuous"


def test_on_moves_only_bushes():
    """Same seeds on vs off: only bush positions differ, and some do."""
    p_off = _params(_lvl05_dict(bush_min_fire_distance=0))
    p_on = _params(_lvl05_dict(bush_min_fire_distance=3))
    s_off, s_on = _resets(p_off, 256), _resets(p_on, 256)
    _, bush = _masks(p_on)
    leaves_off = dict((jax.tree_util.keystr(k), np.asarray(x))
                      for k, x in jax.tree_util.tree_flatten_with_path(s_off)[0])
    leaves_on = dict((jax.tree_util.keystr(k), np.asarray(x))
                     for k, x in jax.tree_util.tree_flatten_with_path(s_on)[0])
    for k in leaves_off:
        if k == ".obs_pos":
            continue
        assert np.array_equal(leaves_off[k], leaves_on[k]), f"{k} differs with the rule on"
    op_off, op_on = leaves_off[".obs_pos"], leaves_on[".obs_pos"]
    assert np.array_equal(op_off[:, ~bush], op_on[:, ~bush]), "a non-bush obstacle moved"
    moved = int((op_off[:, bush] != op_on[:, bush]).any(-1).sum())
    assert moved > 0, "no bush moved: the rule-on world is not different"


def test_on_changes_the_reset_graph():
    """Contrast: at v > 0 the reset graph differs, so off-parity is not vacuous."""
    p_off = _params(_lvl05_dict(bush_min_fire_distance=0))
    p_on = _params(_lvl05_dict(bush_min_fire_distance=3))
    s0 = core.jax_reset(p_off, jax.random.PRNGKey(0))
    a = jaxpr_shas(jax, jnp, core, p_off, s0)
    b = jaxpr_shas(jax, jnp, core, p_on, s0)
    assert a["jax_reset"] != b["jax_reset"]
    assert a["jax_step"] == b["jax_step"], "the rule must not touch the step graph"


def test_existing_rules_still_hold_when_on():
    v, m = 3, 4
    params = _params(_lvl05_dict(bush_min_fire_distance=v, food_min_fire_distance=m))
    states = _resets(params)
    fire, _ = _masks(params)
    violations, out_of_area, shared = _check_world(params, states, v)
    assert (violations, out_of_area, shared) == (0, 0, 0)
    obs_pos = np.asarray(states.obs_pos)
    act = np.asarray(states.obs_active)
    fp = obs_pos[:, fire]
    fa = act[:, fire]
    dff = _manhattan(fp, fp)
    both = fa[:, :, None] & fa[:, None, :] & ~np.eye(fire.sum(), dtype=bool)[None]
    sep = params.thermal_min_fire_separation
    assert not ((dff < sep) & both).any(), "two burning fires closer than min_fire_separation"
    food = np.asarray(params.res_type) == 0
    rp = np.asarray(states.res_pos)[:, food]
    ra = np.asarray(states.res_active)[:, food]
    dfood = _manhattan(rp, fp)
    assert not ((dfood < m) & ra[:, :, None] & fa[:, None, :]).any(), (
        f"food at Manhattan < {m} from a fire")


# ── 3. the loader ─────────────────────────────────────────────────────────────

def _two_bush_entries():
    """Config-wide vs per-entry reading of the §A3 bound (plan M2).

    Level 05 at count_high: fire slots 3, other slots 32 (resources 16, animals 4,
    rocks 12), bush entry `bush` 10 slots over the whole 10x10 grid. Add a second bush
    entry `shrub`, 3 slots, area 1-based [[2, 2], [8, 9]] -> 0-based rows [1, 8) x cols
    [1, 9) = 7 x 8 = 56 cells. At v = 2, D(2) = 5, so for the shrub area:
      per-entry reading   (shrub's own 3 slots):        56 - 3*5 - 32 = 9 >= 3  -> PASSES
      config-wide reading (10 bush + 3 shrub = 13):     56 - 3*5 - 32 = 9 <  13 -> REFUSED
    (The whole-grid `bush` area passes either way: 100 - 15 - 32 = 53 >= 13.)
    The loader must refuse it: bushes of the larger entry can sit inside the shrub area.
    """
    d = _lvl05_dict(bush_min_fire_distance=2)
    shrub = copy.deepcopy(_obstacle(d, "bush"))
    shrub["name"] = "shrub"
    _fix_count(shrub, 3)
    shrub["area"] = [[2, 2], [8, 9]]     # 1-based inclusive -> rows 1..7, cols 1..8: 7x8
    shrub.pop("edge_margin", None)
    d["environment"]["obstacles"].append(shrub)
    return d


def _mut(fn):
    d = _lvl05_dict(bush_min_fire_distance=3)
    fn(d)
    return d


def _no_fire(d):
    _fix_count(_obstacle(d, "campfire"), 0)


def _no_bush(d):
    _obstacle(d, "bush")["hides_agent"] = False


def _warm_bush(d):
    fire = _obstacle(d, "campfire")
    _obstacle(d, "bush")["temperature_ratio"] = copy.deepcopy(fire["temperature_ratio"])


def _fire_hides(d):
    _obstacle(d, "campfire")["hides_agent"] = True


def _warm_food(d):
    fire = _obstacle(d, "campfire")
    d["environment"]["resources"][0]["temperature_ratio"] = copy.deepcopy(
        fire["temperature_ratio"])


def _per_type(d):
    d["environment"].setdefault("placement", {})["mode"] = "per_type"


def _infeasible(d):
    """5x5 grid, 3 fires, 10 bushes: 25 - 3*13 - others < 10 at v = 3."""
    d["environment"]["height"] = 5
    d["environment"]["width"] = 5
    for blk in ("obstacles", "resources", "entities"):
        for e in d["environment"][blk]:
            e["area"] = [[1, 1], [5, 5]]
            e.pop("edge_margin", None)
    _fix_count(_obstacle(d, "campfire"), 3)
    _fix_count(_obstacle(d, "bush"), 10)


_REFUSALS = [
    ("negative", lambda: _lvl05_dict(bush_min_fire_distance=-1),
     r"bush_min_fire_distance must be 0 \(off\) or >= 2"),
    ("one", lambda: _lvl05_dict(bush_min_fire_distance=1),
     r"bush_min_fire_distance must be 0 \(off\) or >= 2.*1 would block only"),
    ("per_type", lambda: _mut(_per_type),
     r"bush_min_fire_distance are not\s+supported under environment\.placement\.mode: per_type"),
    ("no_fire_slot", lambda: _mut(_no_fire), r"no obstacle slot is a heat source"),
    ("no_bush_slot", lambda: _mut(_no_bush), r"no obstacle slot has hides_agent"),
    ("bush_is_fire", lambda: _mut(_fire_hides), r"both a heat source and hides_agent"),
    ("warm_bush_entry", lambda: _mut(_warm_bush), r"both a heat source and hides_agent"),
    ("resource_heat_source", lambda: _mut(_warm_food), r"resource slot\(s\) are heat sources"),
    ("infeasible_5x5", lambda: _mut(_infeasible), r"is infeasible for bush entry"),
    ("two_bush_entries_config_wide", _two_bush_entries,
     r"is infeasible for bush entry \['shrub'\].*= 9 < n_bush_slots = 13"),
]


@pytest.mark.parametrize("name,build,pattern", _REFUSALS, ids=[r[0] for r in _REFUSALS])
def test_loader_refusals(name, build, pattern):
    with pytest.raises(ValueError, match=pattern):
        _params(build())


def test_level05_feasibility_margin_logged(caplog):
    """CP5: the logged §A3 margin for level 05 at v = 3 (and 2) matches the plan (19 / 43)."""
    import logging
    with caplog.at_level(logging.INFO, logger="src.environment.config_loader"):
        _params(_lvl05_dict(bush_min_fire_distance=3))
        _params(_lvl05_dict(bush_min_fire_distance=2))
    msgs = [r.getMessage() for r in caplog.records if "bush-fire clearance feasible" in r.getMessage()]
    assert any("100 - 3*13 - 32 = 29 >= n_bush 10 (margin 19)" in m for m in msgs), msgs
    assert any("100 - 3*5 - 32 = 53 >= n_bush 10 (margin 43)" in m for m in msgs), msgs


def test_missing_key_raises_when_thermal_on():
    d = _lvl05_dict()
    del d["thermal"]["bush_min_fire_distance"]
    with pytest.raises(ValueError, match=r"thermal\.bush_min_fire_distance.*required but missing"):
        _params(d)


def test_thermal_off_needs_no_key():
    d = _lvl05_dict(enabled=False)
    del d["thermal"]["bush_min_fire_distance"]
    assert _params(d).thermal_bush_min_fire_distance == 0
