"""The V2 render entry point writes videos WITHOUT disturbing the V1 pipeline.

WHAT THIS FILE PROTECTS, IN PLAIN WORDS. The project has two episode-video
renderers. The new one (`scripts/eval/render_recordings_v2.py`) is what training
and evaluation call, and it writes into a folder called `videos_v2/` — so as of
2026-09-17 these tests protect the DEFAULT render path, not a side experiment.
The previous one (`scripts/eval/render_recordings.py`) is a frozen file that
remains runnable by hand and still writes into `videos/`. The user's condition
for the whole redesign was that the old path keeps working untouched, so these
tests render the SAME recordings directory with BOTH scripts and check that the
old one's output files are byte-for-byte what they were before the new one ran,
and that the new one put nothing whatsoever inside `videos/`.

THE OTHER TWO PROPERTIES. A written MP4 must decode to exactly as many frames as
the recording has steps -- a video that silently drops a frame is the failure the
frame count exists to make visible -- and `--concat` must refuse to glue together
episodes whose dashboards are not the same shape.

WHY THE CONCAT REFUSAL IS TESTED ON THE FUNCTION RATHER THAN ON A DIRECTORY. The
plan asks for a "doctored two-param-set dir". One cannot be built: a recordings
directory has exactly ONE `run_meta.pkl`, every episode in it is rendered from
those same params, and a layout signature is a pure function of the params -- so
two episodes of one directory ALWAYS share a signature, whatever their payloads
contain. The refusal is therefore exercised directly, by handing the guard two
different signatures, and the real-directory case asserts the opposite (that a
genuine run does share one). See the Implementation Report deviation.
"""
import hashlib
import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

_REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_REPO))
sys.path.insert(0, str(_REPO / "scripts" / "eval"))

import render_recordings_v2 as rrv2  # noqa: E402  (bare-name import, §1c)

V1_SCRIPT = _REPO / "scripts" / "eval" / "render_recordings.py"
V2_SCRIPT = _REPO / "scripts" / "eval" / "render_recordings_v2.py"

#: The campfire fixture. Gitignored, regenerated by
#: `scripts/eval/make_render_fixture_recordings.py`.
FIXTURE = _REPO / "results" / "render_audit" / "recordings" / "M4" / "M4"
_MISSING = (f"render-audit fixtures not on disk ({FIXTURE}); regenerate with "
            f"scripts/eval/make_render_fixture_recordings.py")

#: The 24-step episode -- the short one, so a full V1 + V2 render stays affordable.
EPISODE = "episode_000001.rec.gz"


def _env():
    """CPU-only, so a test can never reach for a training GPU."""
    env = dict(os.environ)
    env["JAX_PLATFORMS"] = "cpu"
    env["CUDA_VISIBLE_DEVICES"] = ""
    return env


def _run(script, *args):
    return subprocess.run([sys.executable, str(script), *map(str, args)],
                          capture_output=True, text=True, env=_env(), cwd=str(_REPO))


def _sha(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def _tree(path):
    """Every file under `path`, relative, as {name: sha256}. Missing dir -> {}."""
    path = Path(path)
    if not path.exists():
        return {}
    return {str(p.relative_to(path)): _sha(p) for p in sorted(path.rglob("*")) if p.is_file()}


@pytest.fixture
def run_dir(tmp_path):
    """A recordings directory in the layout both scripts expect.

    `<run>/recordings/<pct>/` -- both derive their output folder as
    `<run>/videos*/<pct>/`, i.e. `rec_dir.parent.parent`.
    """
    if not (FIXTURE / "run_meta.pkl").exists():
        pytest.skip(_MISSING)
    rec = tmp_path / "run" / "recordings" / "M4"
    rec.mkdir(parents=True)
    shutil.copy2(FIXTURE / "run_meta.pkl", rec / "run_meta.pkl")
    shutil.copy2(FIXTURE / EPISODE, rec / EPISODE)
    return rec


# --------------------------------------------------------------- fast, no render


def test_there_is_no_way_to_delete_anything():
    """V1 has `--cleanup-per-episode`; V2 deliberately has none.

    The flag is how V1 can remove files, and the plan's §D5.4 requires the new
    entry point to have no deleting code path at all, so this asserts on the
    real interface (what `--help` offers) and on the absence of any deleting call
    in the source. It deliberately does NOT grep the source for the flag NAME:
    the module docstring names it to say it is absent, and a test that cannot
    tell an explanation from an implementation is not measuring anything.
    """
    src = V2_SCRIPT.read_text()
    assert 'add_argument("--cleanup-per-episode"' not in src
    assert "add_argument('--cleanup-per-episode'" not in src
    assert "unlink" not in src and "rmtree" not in src and "shutil.rm" not in src
    out = _run(V2_SCRIPT, "--help")
    assert "--cleanup-per-episode" not in out.stdout
    assert "--concat" in out.stdout and "--skip-existing" in out.stdout


def test_concat_refuses_two_different_layouts():
    """Two shapes in one video is the thing the guard exists to stop."""
    with pytest.raises(SystemExit) as exc:
        rrv2._assert_single_layout({1: "a" * 64, 2: "b" * 64})
    msg = str(exc.value)
    assert "do not share one dashboard layout" in msg
    # It must name the episodes on each side, or the refusal is unactionable.
    assert "episodes 1" in msg and "episodes 2" in msg


def test_concat_accepts_one_layout_and_returns_it():
    assert rrv2._assert_single_layout({1: "a" * 64, 2: "a" * 64}) == "a" * 64
    with pytest.raises(SystemExit):
        rrv2._assert_single_layout({})


# ------------------------------------------------------------------ integration


@pytest.mark.integration
def test_v2_leaves_the_v1_pipeline_byte_identical(run_dir):
    """Render the same recordings with V1 then V2; V1's bytes must not move."""
    run_root = run_dir.parent.parent
    videos, videos_v2 = run_root / "videos", run_root / "videos_v2"

    v1 = _run(V1_SCRIPT, run_dir, "--workers", 1, "--concat")
    assert v1.returncode == 0, v1.stderr[-3000:]
    before = _tree(videos)
    assert before, f"V1 wrote no MP4 under {videos}\n{v1.stdout}\n{v1.stderr[-2000:]}"

    v2 = _run(V2_SCRIPT, run_dir, "--workers", 1, "--concat")
    assert v2.returncode == 0, v2.stderr[-3000:]

    # 1. Not one byte of V1's output moved, and no file was added or removed.
    assert _tree(videos) == before

    # 2. V2's output exists, and lives only under videos_v2/.
    after_v2 = _tree(videos_v2)
    assert f"M4/{EPISODE.replace('.rec.gz', '.mp4')}" in after_v2
    assert "eval_M4.mp4" in after_v2

    # 3. Nothing of V2's leaked anywhere else in the run.
    others = {p for p in run_root.rglob("*.mp4")
              if videos not in p.parents and videos_v2 not in p.parents}
    assert not others, f"MP4s written outside both video folders: {others}"


@pytest.mark.integration
def test_written_mp4_decodes_to_exactly_the_recorded_step_count(run_dir):
    """The checkpoint's own bar: frame count == step count, read back off disk."""
    from src.utils.eval_recording import load_episode

    steps = len(load_episode(run_dir / EPISODE)["snapshots"])
    out = _run(V2_SCRIPT, run_dir, "--workers", 1, "--concat")
    assert out.returncode == 0, out.stderr[-3000:]

    run_root = run_dir.parent.parent
    mp4 = run_root / "videos_v2" / "M4" / EPISODE.replace(".rec.gz", ".mp4")
    # Probed by DECODING the finished file, not by asking the writer.
    assert rrv2.probe_frame_count(mp4) == steps
    # The concatenation of one episode is that episode, frame for frame.
    assert rrv2.probe_frame_count(run_root / "videos_v2" / "eval_M4.mp4") == steps


@pytest.mark.integration
def test_skip_existing_looks_only_in_its_own_folder(run_dir):
    """A V1 MP4 at the matching name must NOT make V2 skip the episode."""
    run_root = run_dir.parent.parent
    mp4_name = EPISODE.replace(".rec.gz", ".mp4")

    assert _run(V2_SCRIPT, run_dir, "--workers", 1).returncode == 0
    v2_mp4 = run_root / "videos_v2" / "M4" / mp4_name
    assert v2_mp4.exists()

    # Same episode already rendered under videos_v2/ -> skipped.
    again = _run(V2_SCRIPT, run_dir, "--workers", 1, "--skip-existing")
    assert again.returncode == 0
    assert "already rendered" in again.stdout

    # Now only a V1-shaped file exists. V2 must render anyway: it never looks
    # at videos/, so a V1 video can neither satisfy nor block it.
    v2_mp4.unlink()
    (run_root / "videos" / "M4").mkdir(parents=True, exist_ok=True)
    (run_root / "videos" / "M4" / mp4_name).write_bytes(b"not a real mp4")

    third = _run(V2_SCRIPT, run_dir, "--workers", 1, "--skip-existing")
    assert third.returncode == 0, third.stderr[-3000:]
    assert v2_mp4.exists(), "V2 skipped an episode on the strength of a videos/ file"
    assert (run_root / "videos" / "M4" / mp4_name).read_bytes() == b"not a real mp4"


@pytest.mark.integration
def test_one_real_run_shares_one_layout_signature(run_dir):
    """The other half of the concat rule: it must not trip on a genuine run."""
    from src.environment.dashboard import EpisodeRenderer
    from src.utils.eval_recording import load_episode, load_run_meta

    meta = load_run_meta(FIXTURE)
    sigs = {}
    for ep in sorted(FIXTURE.glob("episode_*.rec.gz")):
        r = EpisodeRenderer(meta["params"], meta["icon_config"], load_episode(ep),
                            action_map=meta.get("action_map"))
        try:
            sigs[ep.name] = r.layout_signature()
        finally:
            r.close()
    assert len(sigs) > 1, "need at least two episodes for this to mean anything"
    assert rrv2._assert_single_layout(sigs)  # must not raise


@pytest.mark.integration
def test_an_unrenderable_recording_fails_loudly_and_alone(tmp_path, run_dir):
    """A corrupt episode is reported in full; its neighbours still render.

    This is the behaviour the pre-thermal trained-policy recordings (M7-M9) need:
    they carry an archived `EnvParams` with no `thermal_enabled` field and raise
    inside the frozen observation breakdown. The batch must not abort, and the
    exit code must not claim success.
    """
    broken = run_dir / "episode_000099.rec.gz"
    broken.write_bytes(b"this is not a gzip payload")

    out = _run(V2_SCRIPT, run_dir, "--workers", 1)
    assert out.returncode != 0, "a failed recording must not exit 0"
    assert "episode_000099" in out.stderr
    assert "could not be rendered" in out.stderr
    assert "Traceback" in out.stderr, "the failure must be reported in full"

    # The good episode still rendered.
    good = (run_dir.parent.parent / "videos_v2" / "M4"
            / EPISODE.replace(".rec.gz", ".mp4"))
    assert good.exists()
    assert rrv2.probe_frame_count(good) > 0


@pytest.mark.integration
def test_a_recording_with_no_true_observations_renders(tmp_path):
    """CP4 — the `true_obs=None` shape renders, and its frame count is exact.

    This is the ORDINARY recording shape rather than an exotic one: dreamer-srl
    never records noise-free observations at all, and recurrent PPO omits them on
    any video-only evaluation of a world without perceptual noise. Cell M6b is
    the demanding version — perceptual noise is ON while the noise-free
    comparison is ABSENT, the combination that drives the "not recorded" caption.

    M6b is genuine production-writer output (`make_render_fixture_recordings.py`
    with `no_true_obs=True`). A hand-doctored payload was deliberately rejected:
    it would risk testing an artefact of the edit rather than the real shape.
    """
    from src.utils.eval_recording import load_episode

    cell = _REPO / "results" / "render_audit" / "recordings" / "M6b" / "M6b"
    if not (cell / "run_meta.pkl").exists():
        pytest.skip(f"render-audit fixture M6b not on disk ({cell}); regenerate "
                    f"with scripts/eval/make_render_fixture_recordings.py")

    rec = tmp_path / "run" / "recordings" / "M6b"
    rec.mkdir(parents=True)
    shutil.copy2(cell / "run_meta.pkl", rec / "run_meta.pkl")
    for ep in sorted(cell.glob("episode_*.rec.gz")):
        shutil.copy2(ep, rec / ep.name)

    # The shape under test really is the one this test claims to cover.
    steps = 0
    for ep in sorted(rec.glob("episode_*.rec.gz")):
        payload = load_episode(ep)
        assert payload.get("true_obs") is None, f"{ep.name} carries true_obs"
        steps += len(payload["snapshots"])

    out = _run(V2_SCRIPT, rec, "--workers", 1, "--concat")
    assert out.returncode == 0, out.stderr[-3000:]

    consolidated = tmp_path / "run" / "videos_v2" / "eval_M6b.mp4"
    assert rrv2.probe_frame_count(consolidated) == steps
